spring:

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
    database: mysql

  messages:
    basename: messages/validation
    encoding: UTF-8
    fallbackToSystemLocale: false
    alwaysUseMessageFormat: true

  config:
    import: application-secret.yml
  data:
    redis:
      host: localhost
      port: 6379